### ISSUE TITLE
NPE in DigitsClient.createAccount

### ISSUE THREAD

**Issue by PatrickDattilio** [twitter/digits-android#14]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.digits.sdk.android.DigitsApiProvider$SdkService com.digits.sdk.android.DigitsApiProvider.getSdkService()' on a null object reference
       at com.digits.sdk.android.DigitsClient.createAccount(DigitsClient.java:102)
       at com.digits.sdk.android.ConfirmationCodeController.executeRequest(ConfirmationCodeController.java:60)
       at com.digits.sdk.android.DigitsActivityDelegateImpl$1.onClick(DigitsActivityDelegateImpl.java:42)
       at android.view.View.performClick(View.java:5197)
       at android.view.View$PerformClick.run(View.java:20926)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by efrohnhoefer** [comment]
Hi @PatrickDattilio Thank for the issue report. The error has been resolved in today's release. Here is the note I posted on [Twitter Community](https://twittercommunity.com/t/digitskit-twitterkit-hotfix/46800).
