### ISSUE TITLE
java.lang.IllegalAccessError: This activity can only be started from Digits

### ISSUE THREAD

**Issue by dustedrob** [twitter/digits-android#33]
Crashlytics reported this crash a moments ago. I'm not sure how to reproduce it but here's the log. The version used is 1.8.0.  

  Fatal Exception: java.lang.IllegalAccessError: This activity can only be started from Digits
       at com.digits.sdk.android.DigitsActionBarActivity.onCreate(DigitsActionBarActivity.java)
       at android.app.Activity.performCreate(Activity.java)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.access$800(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by efrohnhoefer** [comment]
We see this frequently. I believe this is due to automated testing by third-parties. I am going to close the issue unless you have more information.

**Comment by dustedrob** [comment]
Well, it was a crash report from an end user so i really doubt it had anything to do with automated testing but I'm afraid i can't offer any more information.

**Comment by assiziv** [comment]
@efrohnhoefer we see this crash happening to ~600 real users. I'd be really happy if we can get to the bottom of this. Below is the stack trace. It happens on various devices and Android versions. LMK if you need any further information.

Fatal Exception: java.lang.IllegalAccessError: This activity can only be started from Digits
       at com.digits.sdk.android.DigitsActivity.onCreate(DigitsActivity.java:45)
       at com.digits.sdk.android.PhoneNumberActivity.onCreate(PhoneNumberActivity.java:25)
       at android.app.Activity.performCreate(Activity.java:6912)

**Comment by efrohnhoefer** [comment]
@assiziv I am no longer part of the Fabric/Digits team but I am sure @ashwinraghav can hep you out.

**Comment by assiziv** [comment]
Thanks @efrohnhoefer. Do you think @ashwinraghav is still apart of the team? Is he watching this?

**Comment by mikebonnell** [comment]
Hey @PravinsinghWaghela ,

Digits is no longer offered or supported as it was shutdown October 2, 2017 - http://get.digits.com/blog

I'd recommend replacing Digits with Firebase Auth: https://firebase.google.com/docs/auth/

**Comment by PravinsinghWaghela** [comment]
@mikebonnell ,
Thanks for your reply. But I have not used digits. Can you please expain where can i had implemented digits? I am using OneSignal for Push Notification, Facebook and Twitter Login and Fabric Crashlytics. As I am not able to find any usage of Digit. Nor does the crash report explains where the use of Digit is made in my project.
