### ISSUE TITLE
Please check your network connection

### ISSUE THREAD

**Issue by guptavps** [twitter/digits-android#49]
This phone number is giving the error.  +919874709009. Can you please check the problem here. My users are stuck, Digits has a number of problems and SMS codes are not getting sent. Is there a daily max limit per app per day registered in Digits ? This phone number is not associated with a Twitter account either as you suggested in another issue.

**Comment by ashwinraghav** [comment]
Hey @guptavps 
We were able to determine that you were able to successfully verify this phone number a few minutes after you posted this. There are no limits on the number of phoneNumbers that can be verified per app. There are limits on how many time a particular number attempts verification. If you kicked off the registration multiple times for the above number, you may have run into a rate limit?
Are there other symptoms that your users are seeing?

**Comment by guptavps** [comment]
Thanks Ashwin for quick follow up. Yes the user was able to log in subsequently but why not in the first attempt despite trying several times ??

This is the only problem i am facing with Digits so far that my users are getting "try again" or "check your network connection" errors at times.

Is Digits doing something about it ? This is very important otherwise users will leave the app or stop using it, hope you understand.

When is the next Digits release planned ? I am using latest version - 1.9.2. Will this be fixed in next release ? Please enlighten us as many users are having this issue.



________________________________

**Comment by ashwinraghav** [comment]
Hey @guptavps ,
Thanks for your patience and working with us on this. We are actively investigating the problem since we have had other people complaining about it as well. We are working on fixes that have better error messaging to start off. Il keep the thread updated once we identify and fix the problem .
Having said that, if a user faces this several times, it is likely that they did not have an internet connection / were in a lossy n/w. The other cases we have heard off are sporadic one-off cases and not a stream of continuous errors. Thoughts?

**Comment by guptavps** [comment]
Your assumption about user having lossy network is incorrect my friend. We would not have complained had it been so. Apart from this notorious network connection problem, I am also getting  this below stack trace ("Try Again" error message) at times quite frequently. I want to know what Fabric Digits is doing about it or we will have to rethink our decision to implement it in our app.


E/Twitter: Unexpected response:
                                                          java.lang.IllegalStateException: Not a JSON Object: null
                                                              at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
                                                              at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:136)
                                                              at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:125)
                                                              at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:58)
                                                              at com.twitter.sdk.android.core.TwitterApiException.convert(TwitterApiException.java:110)
                                                              at com.twitter.sdk.android.core.Callback.failure(Callback.java:45)
                                                              at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/Digits: HTTP Error: 503 Service Temporarily Unavailable, API Error: 0, User Message: Try Again
E/Digits: HTTP Error: 401 Authorization Required, API Error: 32, User Message: Try Again




________________________________

**Comment by se-bastiaan** [comment]
I am also getting this error:

```
01-19 12:32:59.295 24222-24222/com.dayhaps.debug E/Twitter: Unexpected response: 
                                                            java.lang.IllegalStateException: Not a JSON Object: null
                                                                at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
                                                                at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:136)
                                                                at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:125)
                                                                at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:58)
                                                                at com.twitter.sdk.android.core.TwitterApiException.convert(TwitterApiException.java:110)
                                                                at com.twitter.sdk.android.core.Callback.failure(Callback.java:45)
                                                                at retrofit1.CallbackRunnable$2.run(CallbackRunnable.java:53)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
01-19 12:32:59.296 24222-24222/com.dayhaps.debug E/Digits: HTTP Error: 503 Service Temporarily Unavailable, API Error: 0, User Message: Try Again
```

However, the SMS is sent and received.

**Comment by ashwinraghav** [comment]
@guptavps @se-bastiaan 
Thanks for the updates and for providing a stack trace. A 503 without an error code is generally indicative of service outages. We wish to acknowledge that the past couple of weeks have been a bit rough in terms of incidents. (We are in the middle of an incident right now.) If you are continuing to see errors, we are happy to hear them.

@guptavps : Do you also have a stack trace you can provide for the network connection problem as well? I might be able to help you out better if I had that. Thanks again for working with us

**Comment by dustedrob** [comment]
@ashwinraghav is it possible that issue #44 is also related to network outages? Our users have been receiving this two errors without apparent cause.

**Comment by efrohnhoefer** [comment]
The 503 was related to a service outage. I added some new information to #44.
