### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid partner key

### ISSUE THREAD

**Issue by hemant1109** [twitter/digits-android#56]
i am trying to use your sample code as you said. but giving this error. also not found any guidance for set partner key. So please give me some instruction for this.  Thanks in advance.

Error in detail:
java.lang.IllegalArgumentException: Invalid partner key
                                                                            at com.digits.sdk.android.DigitsClient.startSignUp(**DigitsClient.java:115**)
                                                                            at com.digits.sdk.android.Digits.authenticate(**Digits.java:147**)
                                                                            at com.example.app.digits.CustomPhoneNumberActivity$3.onClick(**CustomPhoneNumberActivity.java:73**)
                                                                            at android.view.View.performClick(View.java:5201)
                                                                            at android.view.View$PerformClick.run(View.java:21163)
                                                                            at android.os.Handler.handleCallback(Handler.java:746)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by efrohnhoefer** [comment]
Can you share you code? Digits should be used as follows. Custom phone number UI is a feature available to select partners at the moment.

```
   DigitsAuthConfig.Builder digitsAuthConfigBuilder = new DigitsAuthConfig.Builder()
      .withAuthCallBack(callback)
      .withPhoneNumber("")
      .withEmailCollection()
      .withThemeResId(R.style.LightTheme);
```

**Comment by hemant1109** [comment]
Thanks for reply. But i wanted to create custom phone number screen. So i use github sample code for testing. but some how this error occurred. please let me know how to use custom phone number screen. 

Thanks in advance.

**Comment by efrohnhoefer** [comment]
Please email support at fabric.io requesting access to this feature. Please provide a description of you application.

**Comment by akbotsa** [comment]
What is partnerKey that i need to pass confirmation callback ?

**Comment by mikebonnell** [comment]
As @efrohnhoefer mentioned above - please email support at fabric.io requesting access to this feature and provide a description of you application.

**Comment by goznauk** [comment]
I've found a private method to get partner key by consumer key in DigitsClient class.
It's quite simple, so I've just copied this to my code.

''' java
    private String getPartnerKeyByConsumerKey(String consumerKey) {
        final String toEncode = "__Digits@P@rtner__" + consumerKey;
        return Base64.encodeToString(toEncode.getBytes(Charset.forName("UTF-8")), Base64.NO_WRAP);
    }
'''

I've made simple util class about this.

check this gist
https://gist.github.com/goznauk/4c31cf38b1a0ea3e93e827153fe85553

**Comment by goznauk** [comment]
I've found a private method to get partner key by consumer key in DigitsClient class.
It's quite simple, so I've just copied this to my code.

'''
    private String getPartnerKeyByConsumerKey(String consumerKey) {
        final String toEncode = "__Digits@P@rtner__" + consumerKey;
        return Base64.encodeToString(toEncode.getBytes(Charset.forName("UTF-8")), Base64.NO_WRAP);
    }
'''

I've made simple util class about this.

check this gist
https://gist.github.com/goznauk/4c31cf38b1a0ea3e93e827153fe85553

**Comment by goznauk** [comment]
I've found a private method to get partner key by consumer key in DigitsClient class.
It's quite simple, so I've just copied this to my code.

``` java
    private String getPartnerKeyByConsumerKey(String consumerKey) {
        final String toEncode = "__Digits@P@rtner__" + consumerKey;
        return Base64.encodeToString(toEncode.getBytes(Charset.forName("UTF-8")), Base64.NO_WRAP);
    }
```

I've made simple util class about this.

check this gist
https://gist.github.com/goznauk/4c31cf38b1a0ea3e93e827153fe85553
