### ISSUE TITLE
FailureActivity throwing exception when clicking the dismiss button

### ISSUE THREAD

**Issue by ahmedgalal** [twitter/digits-android#68]
Using digits version 1.11.0@aar

Enter an invalid number for a few times and you will get the FailureActivity, clicking the Dismiss button on this activity will throw a fatal exception, here is the error stack:

```
Fatal Exception: java.lang.IllegalArgumentException: Incomplete DigitsEventDetails object com.digits.sdk.android.DigitsEventDetails{language='ar',elapsedTimeInMillis='130591'}
       at com.digits.sdk.android.FailFastEventDetailsChecker.throwIncompleteDetailsExWhenFalse(FailFastEventDetailsChecker.java:255)
       at com.digits.sdk.android.FailFastEventDetailsChecker.loginFailure(FailFastEventDetailsChecker.java:46)
       at com.digits.sdk.android.DigitsEventCollector.authFailure(DigitsEventCollector.java:71)
       at com.digits.sdk.android.LoginResultReceiver.onReceiveResult(LoginResultReceiver.java:67)
       at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:52)
       at android.os.ResultReceiver.send(ResultReceiver.java:86)
       at com.digits.sdk.android.FailureControllerImpl.sendFailure(FailureControllerImpl.java:47)
       at com.digits.sdk.android.FailureActivityDelegateImpl$1.onClick(FailureActivityDelegateImpl.java:85)
       at android.view.View.performClick(View.java:4439)
       at android.widget.Button.performClick(Button.java:148)
       at android.view.View$PerformClick.run(View.java:18395)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by efrohnhoefer** [comment]
Thank you for the issue report. We also discovered this after release. We are working on updating the library now.

**Comment by ahmedgalal** [comment]
Thanks for the info, i'll be waiting for the update.

**Comment by efrohnhoefer** [comment]
This should be updated now. Current version is 11.11.1.
