### ISSUE TITLE
NPE crash if i try my app with digits login on a genymotion emulator or a mobile device

### ISSUE THREAD

**Issue by aldefy** [twitter/digits-android#8]
```
java.lang.RuntimeException: Unable to resume activity {x.ytz/com.digits.sdk.android.PhoneNumberActionBarActivity}: java.lang.NullPointerException

 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2774)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.support.v7.internal.app.WindowDecorActionBar.getDecorToolbar(WindowDecorActionBar.java:248)
            at android.support.v7.internal.app.WindowDecorActionBar.init(WindowDecorActionBar.java:201)
            at android.support.v7.internal.app.WindowDecorActionBar.<init>(WindowDecorActionBar.java:176)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:174)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:90)
            at android.support.v7.app.AppCompatDelegateImplV7.onPostResume(AppCompatDelegateImplV7.java:229)
            at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:139)
            at android.app.Activity.performResume(Activity.java:5323)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aldefy** [comment]
My custom theme that causes the above crash : 

How do you theme the Use My Phone Number button color ???

  <style name="CustomDigitsTheme" parent="Theme.AppCompat.Light">
        <item name="android:textColorPrimary">@android:color/black</item>
        <item name="android:textColorSecondary">@android:color/darker_gray</item>
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:textColorLink">#ff398622</item>
        <item name="colorAccent">#ff398622</item>
        <item name="dgts__accentColor">#ff398622</item>
    </style>

**Comment by efrohnhoefer** [comment]
Hi @aldefy,

What version of appcompat are you using? What version of Android is your emulator running? We recently received a similar report but have been unable to reproduce. Any additional information/code you can share would be helpful. Also please feel free to email support@fabric.io.

**Comment by efrohnhoefer** [comment]
Hi @aldefy Looks like this is likely an issue with `appcompat-v7:22.+`. Earlier versions of the appcompat library should work.

See: [Issue 175802](https://code.google.com/p/android/issues/detail?id=175802)

**Comment by aldefy** [comment]
Hi , sorry could reply earlier , i'll will check this out and get back ,thanks for reply
